name: Auto Package Tailscale Scripts

on:
  push:
    paths:
      - "scripts/*"

permissions:
  contents: write

jobs:
  package_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Create tarball
        run: |
          mkdir -p package
          cp scripts/* package/
          tar -czvf tailscale-openwrt-scripts.tar.gz -C package .

      - name: Checkout tailscale-openwrt repo
        uses: actions/checkout@v4
        with:
          repository: CH3NGYZ/tailscale-openwrt
          token: ${{ secrets.PUSH_TOKEN }}
          path: openwrt_repo

      - name: Copy tarball to openwrt repo
        run: |
          cp tailscale-openwrt-scripts.tar.gz openwrt_repo/dist/
          cd openwrt_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/tailscale-openwrt-scripts.tar.gz
          git commit -m "Update packaged tailscale scripts"
          git push
